import java.io.IOException;
import java.util.Arrays;

import org.mapdb.Atomic.Var;
import org.mapdb.DB;
import org.mapdb.DBMaker;
import org.mapdb.DataInput2;
import org.mapdb.DataOutput2;
import org.mapdb.IndexTreeList;
import org.mapdb.Serializer;
import org.mapdb.serializer.SerializerIntArray;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class Main {
    public static void main(String[] args) {
    	
		DB db = DBMaker.fileDB("file.db")
				.concurrencyDisable()
				.make();
		
		IndexTreeList<String> list = db.indexTreeList("list", Serializer.STRING).createOrOpen();
		
		System.out.println(String.join("\n", list));
		 
		db.close();
	}
    
    private static class Manga {
    	private int id;
    	private String name;
    	
		public Manga(int id, String name) {
			this.id = id;
			this.name = name;
		}

		@Override
		public String toString() {
			return "Manga [id=" + id + ", name=" + name + "]";
		}
		
		
    }
    
    static class MangaSerilizer implements Serializer<Manga>{
		@Override
		public void serialize(DataOutput2 out, Manga value) throws IOException {
			out.writeInt(value.id);
			out.writeUTF(value.name);
		}

		@Override
		public Manga deserialize(DataInput2 input, int available) throws IOException {
			return new Manga(input.readInt(), input.readUTF());
		}
    	
    }
}
